### ISSUE TITLE
Race condition in Done()

### ISSUE THREAD

**Issue by mgsouth** [zaininfo/context-wait#1]
There's a race condition in Done() between ctx.Value() and close(); two goroutines simultaneously calling Done() can both see Value() ok, then second one calling close() will panic.

Mixing multiple concurrency coordinators (in this case a context and a channel) is tricky, and Go adds little gotchas to the mix. You need a mutex to make all operations atomic across both the context and channel.

**Comment by zaininfo** [comment]
Thanks for reporting this.
It should be fixed by 4101f868abc019cfcdf53f83088195bd923c6aea.

**Comment by zaininfo** [comment]
Actually, this was not fixed by 4101f868abc019cfcdf53f83088195bd923c6aea, but e96a104f91513243543c2d92a433d215ccc95131 fixes it.
